apiVersion: v1
kind: Service
metadata:
  name: safle
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: safle
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: safle
spec:
  defaultBackend:
    service:
      name: safle
      port:
        number: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: safle
spec:
  replicas: 2
  selector:
    matchLabels:
      app: safle
  template:
    metadata:
      labels:
        app: safle
    spec:
      containers:
      - name: safle
        image: SAFLE_IMAGE
        ports:
          - containerPort: 3000
        resources:
          limits:
            memory: 1024Mi
          requests:
            memory: 256Mi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: safle
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: safle
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50